lane :codesigning do
  match(type: "appstore")
end

lane :appstore do
  appicon(
    appicon_devices: [:iphone],
    appicon_image_file: "./watch.user/Assets.xcassets/AppIcon.appiconset/AppIcon.png",
    appicon_path: "./watch.user/Assets.xcassets/"
  )
  codesigning
  gym(scheme: "watch.user")
  deliver(force: true, submit_for_review: true)
end
